module Register
  KNOWN = [
    
    #LOTTO
    { word: "gull", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "knallgode", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kupp", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "vinn", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "lodd", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "rabatt", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "salg", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "sale", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "justforyou", plural: false, comment: "Bør omformuleres", state: "exclamation-triangle orange" },
    { word: "billig", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "times-circle red" },
    { word: "billi", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "times-circle red" },
    { word: "lagersalg", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "pallesalg", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "gratulerer", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "bonus", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "tilbud", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "deal", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "trekk", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "trekning", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "avslag", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "gave", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "påskekampanje", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "megakampanje", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "forhandlerkampanje", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "salgskampanje", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kolleksjonssalg", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" }, 
    { word: "kampanje", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "jackpot", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kampanjer", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "tilbudsdag", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kjempetilbud", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "gavekort", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "gratis", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "grattis", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "bestselge", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "fordel", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kupong", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "gullkupong", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kupongdag", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kjempetilbud", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "lotteri", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "pris", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kontant", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "knallpris", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "spill", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kjøp", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kunngjøring", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "vekt", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "hast", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "vikig", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "velkomstgave", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "lotto", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },

    
    #TEST
    { word: "test", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "lorem", plural: false, comment: "Forbindes med tester og kan fort ende opp i søppelkassen.", state: "exclamation-triangle orange" },
    { word: "ipsum", plural: false, comment: "Forbindes med tester og kan fort ende opp i søppelkassen.", state: "exclamation-triangle orange" },
    { word: "dolor", plural: false, comment: "Forbindes med tester og kan fort ende opp i søppelkassen.", state: "exclamation-triangle orange" },
    
    #LÅN
    { word: "lån", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "penger", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "konto", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "luksus", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "forbrukslån", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "rente", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kredittkort", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kreditt", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "inntekt", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "bankkonto", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "betalingskort", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "betalingskortet", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "finansiering", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "finansieringen", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "lånetilbud", plural: true, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    
    #MISC
    { word: "øl", plural: false, comment: "Ja takk!", state: "success" },
    { word: "Øl", plural: false, comment: "Ja takk!", state: "success" },
    { word: "Rinnan", plural: false, comment: "Det er er vel fortsatt ikke innafor...", state: "times-circle red" },
    { word: "rinnan", plural: false, comment: "Det er er vel fortsatt ikke innafor...", state: "times-circle red" },
    { word: "faktura", plural: false, comment: "Et ord som vanligvis ikke forbindes med høy åpningsrate. Vurder omformulering.", state: "info-circle blue" },
    { word: "forfalt", plural: false, comment: "Et ord som vanligvis ikke forbindes med høy åpningsrate. Vurder omformulering.", state: "info-circle blue" },
    { word: "forfalte", plural: false, comment: "Et ord som vanligvis ikke forbindes med høy åpningsrate. Vurder omformulering.", state: "info-circle blue" },
    { word: "forfalt(e)", plural: false, comment: "Et ord som vanligvis ikke forbindes med høy åpningsrate. Vurder omformulering.", state: "info-circle blue" },
    { word: "påminnelse", plural: false, comment: "Et ord som vanligvis ikke forbindes med høy åpningsrate. Vurder omformulering.", state: "info-circle blue" },
    { word: "fornyelse", plural: false, comment: "Et ord som vanligvis ikke forbindes med høy åpningsrate. Vurder omformulering.", state: "info-circle blue" },
    { word: "abonnement", plural: false, comment: "Et ord som vanligvis ikke forbindes med høy åpningsrate. Vurder omformulering.", state: "info-circle blue" },
    { word: "kredittid", plural: false, comment: "Et ord som vanligvis ikke forbindes med høy åpningsrate. Vurder omformulering.", state: "info-circle blue" },
        
    #BLACKLIST
    { word: "pikk", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "cock", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "viagra", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "penis", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "enlarge", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "potens", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "kontonummer", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "pin", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "pinkode", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },
    { word: "helvete", plural: false, comment: "Ikke alle liker banning. Vurder omformulering", state: "times-circle red" },
    { word: "helvetes", plural: false, comment: "Ikke alle liker banning. Vurder omformulering", state: "times-circle red" },
    { word: "pille", plural: false, comment: "Hvis du ikke kjenner til dette bør du lese deg opp.", state: "times-circle red" },

    #GENERAL
    { word: "nyhetsbrev", plural: false, comment: "Unngå å fortelle at et nyhetsbrev er et nyhetsbrev. Gi en mer detaljert beskrivelse om hva mailen omhandler.", state: "exclamation-triangle orange" },
    { word: "nyhetsmail", plural: false, comment: "Unngå å fortelle at et nyhetsbrev er et nyhetsbrev. Gi en mer detaljert beskrivelse om hva mailen omhandler.", state: "exclamation-triangle orange" },
    { word: "newsmail", plural: false, comment: "Unngå å fortelle at et nyhetsbrev er et nyhetsbrev. Gi en mer detaljert beskrivelse om hva mailen omhandler.", state: "exclamation-triangle orange" },
    { word: "månadsbrev", plural: false, comment: "Unngå å fortelle at et nyhetsbrev er et nyhetsbrev. Gi en mer detaljert beskrivelse om hva mailen omhandler.", state: "exclamation-triangle orange" },
    { word: "info-circle bluemail", plural: false, comment: "Unngå å fortelle at et nyhetsbrev er et nyhetsbrev. Gi en mer detaljert beskrivelse om hva mailen omhandler.", state: "exclamation-triangle orange" },
    
    #PROMISES
    { word: "fantastisk", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "kaboom", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "gratulerer", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "aldri", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "ekstremt", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "superkvalitet", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "fantastiske", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "eksklusivt", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "eksklusive", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },
    { word: "beste", plural: false, comment: "Økt spamfare. Unngå for mange av disse advarslene i kombinasjon.", state: "exclamation-triangle orange" },

    #NIGERIA
    { word: "hjelp", plural: true, comment: "Økt spamfare. Kan forstås som Nigeria/svindel mail.", state: "exclamation-triangle orange" },
  ]
end